version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mahala
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - mahala
volumes:
  db:
networks:
  mahala: